### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by sathiyarajcbe** [tonyofrancis/Fetch#103]
FileDownloader
                                                                                java.net.SocketTimeoutException
                                                                                    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                                                    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                                    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                    at com.android.okio.Okio$2.read(Okio.java:113)
                                                                                    at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                                                    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
                                                                                    at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                                                    at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
                                                                                    at com.tonyodev.fetch2.downloader.FileDownloaderImpl.writeToOutputInternal(FileDownloaderImpl.kt:164)
                                                                                    at com.tonyodev.fetch2.downloader.FileDownloaderImpl.run(FileDownloaderImpl.kt:70)
                                                                                    at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:45)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by tonyofrancis** [comment]
@sathiyarajcbe This exception is reporting that the server did not respond in a timely fashion. The File Downloader handled the error as expected. Check the url you are trying to reach with a web browser to see if you are having the same issues.
