### ISSUE TITLE
Download is not starting for Oreo 8.0(OnePlus 3T): Fetch 2

### ISSUE THREAD

**Issue by gulshan183** [tonyofrancis/Fetch#104]
Following exception occurs when download is just started. 
` FileDownloader
                                                       com.tonyodev.fetch2.exception.FetchException: request_not_successful
                                                           at com.tonyodev.fetch2.downloader.FileDownloaderImpl.run(FileDownloaderImpl.kt:76)
                                                           at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:45)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                           at java.lang.Thread.run(Thread.java:764)`

Note: The link is responding, And same download is working normally on other OS Versions/Devices

**Comment by tonyofrancis** [comment]
@gulshan183 The error is indicating that the server did not send a response of `HTTP_OK`, `HTTP_ACCEPTED` or `HTTP_PARTIAL`. Can you try using the **okHttpDownloader** with Fetch instead, and testing if that works on the OnePlus 3T device? You can see how to set the okhttp downloader in the **README** under the **Downloaders** section. Waiting to hear back from you.

**Comment by gulshan183** [comment]
@tonyofrancis ,Thanks for update. I got this running after removing the app from optimize battery settings, but the real issue is still unknown. Since it was working with other Oreo devices and I think its related to OP3T device and its settings.

**Comment by tonyofrancis** [comment]
@gulshan183 From the sound of it, it seems that the power saving settings was causing the server response back to Fetch to timeout.
