### ISSUE TITLE
Unhandled Exception Database is closed

### ISSUE THREAD

**Issue by Sergios21** [tonyofrancis/Fetch#111]
After I terminate my application sometimes the main activity crashes with an exception that I cannot handle. Following is the Logcat output:

E/AndroidRuntime: FATAL EXCEPTION: fetch_application           
com.tonyodev.fetch2.exception.FetchImplementationException: database is closed
 at com.tonyodev.fetch2.database.DatabaseManagerImpl.throwExceptionIfClosed(DatabaseManagerImpl.kt:170)
at com.tonyodev.fetch2.database.DatabaseManagerImpl.deleteAll(DatabaseManagerImpl.kt:73)
at com.tonyodev.fetch2.fetch.FetchHandlerImpl.removeAll(FetchHandlerImpl.kt:197)
at com.tonyodev.fetch2.fetch.FetchImpl$removeAll$$inlined$synchronized$lambda$1.run(FetchImpl.kt:233)
                                                                           at android.os.Handler.handleCallback(Handler.java:789)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:180)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by tonyofrancis** [comment]
@Sergios21 I am going to look into this issue. Was on vacation.

**Comment by tonyofrancis** [comment]
@Sergios21 I have fixed this issue and it will be in the next release RC9. Which I should be releasing on Mar 5th, 2018. Thanks
