### ISSUE TITLE
SocketTimeoutException using enableRetryOnNetworkGain

### ISSUE THREAD

**Issue by claudio-jeremias-clansoft** [tonyofrancis/Fetch#123]
I enabled the RetryOnNetworkGain feature, but when my phone goes to flight mode for a very short time I get an exception and UNKNOW error.

`FileDownloader
                                                                              java.net.SocketTimeoutException: Read timed out
                                                                                  at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                                                  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:674)
                                                                                  at com.android.okio.Okio$2.read(Okio.java:113)
                                                                                  at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
                                                                                  at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
                                                                                  at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
                                                                                  at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
                                                                                  at com.tonyodev.fetch2.downloader.FileDownloaderImpl.writeToOutput(FileDownloaderImpl.kt:194)
                                                                                  at com.tonyodev.fetch2.downloader.FileDownloaderImpl.run(FileDownloaderImpl.kt:80)
                                                                                  at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:55)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)`

Do I need to handle something special to make that feature work?

**Comment by tonyofrancis** [comment]
@claudio-jeremias-clansoft Thanks for using Fetch. I have updated Fetch to now catch this exception. So the error now will be Error. CONNECTION_TIMEOUT. Also, if you call `download.getError().getThrowable()` when the error occurs, you will get the throwable that caused the exception to be thrown and act on that. Fetch tries hard to return specific errors, but across many devices and manufacturers the exceptions that are thrown when connection is lost or accessing IO may very. Fetch will label unknown errors as Error.UNKNOWN. Now that the throwable is being returned in this new version (2.0.0-RC12) Fetch gives the library user a chance to handle errors better.

In regards to `RetryOnNetworkGain`, the way Fetch works is that when the connection disconnects or times-out, Fetch then waits about 5 seconds and checks if network is available. If the network is available, Fetch will proceed with the error and mark the download status as `Status.Error`. If  the network is not available after the check, Fetch queues the download until the network becomes available. With that said; there may be instances where connection is lost and after the 5 second wait and network check, the network becomes available and Fetch will still mark the download status with `Status.Error`. Example: Turning on and turning off airplane mode quickly. In cases like these, the library user can also do a network check and if possible call `fetch.retry(download.getId())` to retry the download. A good place to do this in the `FetchListener.onError(@NonNull Download download)` method.

Please check the new version (2.0.0-RC12) and let me know if you encounter any issues.

**Comment by claudio-jeremias-clansoft** [comment]
Good to hear from you @tonyofrancis !!! I am updating the library to RC-12 and also handle that error callback to retry de download!!!
I let you know if I get some new issue.

Regards
