### ISSUE TITLE
Download failed but onError was not called

### ISSUE THREAD

**Issue by anhtuannd** [tonyofrancis/Fetch#126]
I tried Fetch 2 and made download request to unavailable file.
There was error in Logcat, but onError was never called.

`04-10 11:09:06.802 15653-15980/com.humaxdigital.mobile.bracelet E/Main: FileDownloader
                                                                        com.tonyodev.fetch2.exception.FetchException: request_not_successful
                                                                            at com.tonyodev.fetch2.downloader.FileDownloaderImpl.run(FileDownloaderImpl.kt:82)
                                                                            at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:55)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                            at java.lang.Thread.run(Thread.java:762)`

**Comment by anhtuannd** [comment]
Sorry my bad, the listener was clear elsewhere.
