### ISSUE TITLE
AbstractMethodError : Downloader.getRequestSupportedFileDownloaderTypes

### ISSUE THREAD

**Issue by joelphilippage** [tonyofrancis/Fetch#201]
After updating from version 2.1.0-RC15 to 2.2.0-RC1 starting a download crashes the app with the error message 

> 07-24 11:47:35.707 4921-4995/com.turndapage.navcasts E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.turndapage.navcasts, PID: 4921
    java.lang.AbstractMethodError: abstract method "java.util.Set com.tonyodev.fetch2core.Downloader.getRequestSupportedFileDownloaderTypes(com.tonyodev.fetch2core.Downloader$ServerRequest)"
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl.getFileDownloader(DownloadManagerImpl.kt:194)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl.getNewFileDownloaderForDownload(DownloadManagerImpl.kt:186)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by tonyofrancis** [comment]
@joelphilippage thanks for reporting. looking into this

**Comment by tonyofrancis** [comment]
@joelphilippage are you using a custom downloader?. Do you mind sharing your downloader code if you are using a custom downloader?

**Comment by tonyofrancis** [comment]
@joelphilippage unable to replicate. The `getRequestSupportedFileDownloaderTypes(request)` method is implemented for all downloaders. mhmmm. Can you specify the device this error occurs on?. The code you shared with me looks right.

**Comment by tonyofrancis** [comment]
Just released fetch 2.2.0-RC2 with a few fixes. Please test and let me know if this help solve your issue.

**Comment by joelphilippage** [comment]
Seems to be working again. Thanks so much!

I updated and it is working great again. Something could have gone wrong with conflicting dependencies. I was still using
'com.tonyodev.fetch2downloaders:fetch2downloaders:2.2.0-RC1'

But after updating to RC2 it could not longer resolve this dependency. It also said my okhttp3 dependency was out of date after updating to RC2 so I updated that after.

I was testing on the latest Android P developer preview for Wear OS.
