### ISSUE TITLE
 com.tonyodev.fetch2.exception.FetchException: Global Fetch Configuration not set

### ISSUE THREAD

**Issue by Ramkesh9** [tonyofrancis/Fetch#205]
i am posting this after many unsccessful attempts 
i am getting this error at initialiaztion while merging this awesome lib into my app
 rxFetch = RxFetch.Impl.getDefaultRxInstance();
 i dont know what to do , please help me ASAP.

LOGCAT:
Caused by: com.tonyodev.fetch2.exception.FetchException: Global Fetch Configuration not set
        at com.tonyodev.fetch2rx.RxFetch$Impl.getDefaultRxInstance(RxFetch.kt:504)
        at com.kimbl.activity.GameFilesActivity.onCreate(GameFilesActivity.java:63)
        at android.app.Activity.performCreate(Activity.java:6875)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2694)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6379) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by Ramkesh9** [comment]
Oh great , Now Solved, i was not able to get it in doc ,but i got it in
sample , Thanx for responding and also for a nice library.
