### ISSUE TITLE
request_not_successful while downloading from firebase storage

### ISSUE THREAD

**Issue by Chrispassold** [tonyofrancis/Fetch#231]
I need to download an apk file from firebase storage, but this error occurs.

Can anyone help me?

`com.tonyodev.fetch2.exception.FetchException: request_not_successful
        at com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.run(SequentialFileDownloaderImpl.kt:136)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by tonyofrancis** [comment]
@Chrispassold Are you able to access and download the link via a web browser? Are you setting the right authentication headers in the request?

**Comment by Chrispassold** [comment]
@tonyofrancis I fixed it. I adde "Accept" in the header and it works.

`request.addHeader("Accept", "application/vnd.android.package-archive");`
