### ISSUE TITLE
sometimes download error cause by download_incomplete

### ISSUE THREAD

**Issue by runylin** [tonyofrancis/Fetch#240]
When I start download, sometimes received the Exception below, and then download error.   I check the network is normal.

Have you ever encountered a similar problem? What could be the cause?  for help

```
FileDownloader download:DownloadInfo(id=-2082797169, namespace='LibGlobalFetchLib', url='...', file='...', group=4, priority=NORMAL, headers={versionName=..., packageName=..., versionCode=..., size=1271838470, updateDesc=116,101,115,116, policyId=..., name=..., md5=..., isForceUpdate=true, viewType=2}, downloaded=1073342338, total=1271838470, status=DOWNLOADING, error=NONE, networkType=ALL, created=1536303609614, tag=, enqueueAction=REPLACE_EXISTING, identifier=0, downloadOnEnqueue=true, extras={})
                                                                                com.tonyodev.fetch2.exception.FetchException: download_incomplete
                                                                                    at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl.run(ParallelFileDownloaderImpl.kt:137)
                                                                                    at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:97)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                    at java.lang.Thread.run(Thread.java:761)
```

**Comment by tonyofrancis** [comment]
@runylin Are you using the latest version of Fetch?. Does the device have enough space? Are you testing on a physical device or emulator? We need more information to help.

**Comment by runylin** [comment]
I use 2.2.0-RC11 version,  the space in disk is enough also.  And the SoC of testing machine is Hi3751V551, it is a TV platform chip of Huawei Hisilicon .

**Comment by tonyofrancis** [comment]
@runylin Try this. Make sure your gradle file no longer has the com.tonyodev.fetch2downloader.
The  `download_incomplete` is thrown by the parallel downloader when a file did not complete downloading because because the total bytes did not match. Check the logs for errors using this prefix `FileDownloader downloads slice` and post back.

**Comment by runylin** [comment]
@tonyofrancis the gradle not  contains com.tonyodev.fetch2downloader. error log below:
```
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: FileDownloader downloads slice FileSlice(id=-2082797169, position=6, startBytes=1059865360, endBytes=1271838470, downloaded=1986740)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: java.net.SocketTimeoutException: timeout
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.Okio$4.newTimeoutException(Okio.java:232)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.RealBufferedSource.read(RealBufferedSource.java:47)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:440)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$2.run(ParallelFileDownloaderImpl.kt:445)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at java.lang.Thread.run(Thread.java:761)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: Caused by: java.net.SocketException: Socket closed
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at java.net.SocketInputStream.socketRead0(Native Method)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at java.net.SocketInputStream.read(SocketInputStream.java:151)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at java.net.SocketInputStream.read(SocketInputStream.java:120)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.Okio$2.read(Okio.java:140)
09-08 12:47:53.868 11485 11808 E LibGlobalFetchLib: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
```

the readTimeout of OkHttpClient config I use the default value,  should I turn it up?

**Comment by tonyofrancis** [comment]
Sure!

**Comment by tonyofrancis** [comment]
@runylin please let me know if increasing the timeout helped.

**Comment by runylin** [comment]
Unfortunately, It is not help.  below is the config.
```
FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(mContext)
                .setDownloadConcurrentLimit(Runtime.getRuntime().availableProcessors())
                .setHttpDownloader(new OkHttpDownloader(
                        new OkHttpClient.Builder().addInterceptor(new HttpLoggingInterceptor()
                                .setLevel(BASIC))
                                .connectTimeout(Constants.CONNECT_TIMEOUT, TimeUnit.SECONDS)
                                .readTimeout(Constants.READ_TIMEOUT, TimeUnit.SECONDS)
                                .writeTimeout(Constants.WRITE_TIMEOUT, TimeUnit.SECONDS)
                                .build(),
                        Downloader.FileDownloaderType.PARALLEL))
                .enableLogging(BuildConfig.DEBUG)
                .enableRetryOnNetworkGain(true)
                .enableAutoStart(true)
                .setProgressReportingInterval(1000L)
                .build();
```
```
    public static final int CONNECT_TIMEOUT = 60;
    public static final int READ_TIMEOUT = 120;
    public static final int WRITE_TIMEOUT = 60;
```

**Comment by tonyofrancis** [comment]
@runylin Based on the logs and configuration it seems that the server is causing the issue with very slow respond times.
