### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by AliGolmirzaei** [tonyofrancis/Fetch#253]
I received an error report from one of my users as below. It seems due to an unknown error the fetch internal database got corrupted. This error is really rare (in fact happened only once) in my entire usage of fetch. I want to know is there any way to help my user fix this problem except clear data?

**my usage of fetch:**

mainFetch = Fetch.Builder(context, "Main")
.setDownloadConcurrentLimit(5) // Allows Fetch to download 5 downloads in Parallel.
.setDownloader(OkHttpDownloader(okHttpClient))
.setProgressReportingInterval(1000)
.enableRetryOnNetworkGain(true)
//.enableLogging(true)
.build()

**error traceback:**
Error: android.database.sqlite.SQLiteDatabaseCorruptException
************ CAUSE OF ERROR ************

database disk image is malformed (code 11): , while compiling: PRAGMA journal_mode
android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:794)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1148)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
	at com.tonyodev.fetch2.database.DatabaseManagerImpl.<init>(DatabaseManagerImpl.kt:42)
	at com.tonyodev.fetch2.fetch.FetchModulesBuilder$Modules.<init>(FetchModulesBuilder.kt:68)
	at com.tonyodev.fetch2.fetch.FetchModulesBuilder.buildModulesFromPrefs(FetchModulesBuilder.kt:34)
	at com.tonyodev.fetch2.Fetch$Builder.build(Fetch.kt:318)
	at com.tonyodev.fetch2.Fetch$Builder.build(Fetch.kt:298)
	at com.manage.ResourceManager.CheckDownloadFeasibility(ResourceManager.kt:183)
	at com.manage.ResourceManager.StartDownload(ResourceManager.kt:304)
	at com.zapp.common.PlayerActivity.LoadMedia(PlayerActivity.kt:845)
	at com.zapp.common.PlayerActivity.Initialize(PlayerActivity.kt:656)
	at com.zapp.common.PlayerActivity.access$Initialize(PlayerActivity.kt:52)
	at com.zapp.common.PlayerActivity$EmptyWordDatabaseHandler$1.invoke(PlayerActivity.kt:250)
	at com.zapp.common.PlayerActivity$EmptyWordDatabaseHandler$1.invoke(PlayerActivity.kt:52)
	at com.zapp.common.util.ZActivity$Companion$WeakReferenceHandler.handleMessage(ZActivity.kt:793)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: SM-A530F
Model: SM-A530F
Id: LMY48Z
Product: SM-A530F

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: eng.se.infra.20180711.102650

**Comment by AliGolmirzaei** [comment]
Unfortunately, I don't know what is room dependencies. I searched a bit and it seems it is:
![image](https://user-images.githubusercontent.com/25629384/46571929-a7a3cd80-c98a-11e8-81f3-7e36d76bb576.png)

if this is correct then, no I don't have them.

for tags and extras, no I don't use any. 

If it helps I enqueue the download like this:
    val fileTemp = File(file.parent, "temp_${file.name}")
    val request = Request(url, fileTemp.canonicalPath)
    mainFetch!!.enqueue(request)

**Comment by AliGolmirzaei** [comment]
forget to mention I'm using this version


    implementation "com.tonyodev.fetch2:fetch2:2.0.0-RC21"
    implementation "com.tonyodev.fetch2downloaders:fetch2downloaders:2.0.0-RC21"

**Comment by tonyofrancis** [comment]
@AliGolmirzaei 2.0.0-rc21 is no longer supported. I am not aware of any way to fix the database corruption issue. Please use the latest version of Fetch as it has many fixes and improvements.
