### ISSUE TITLE
Download fail file (1KB & 83MB)

### ISSUE THREAD

**Issue by bangdinh** [tonyofrancis/Fetch#302]
Hi Tony.
I using lib. i download with list url. 
Please.Can you help me!. Thank you!
`FileDownloader download:DownloadInfo(id=137256314, namespace='DownloadListActivity', url='https://media.cdnedge.bluemix.net/14658/document/piep-xLlzOxMZ15440032617661544003261766.zip', file='/storage/emulated/0/Download/piepme/piep-xLlzOxMZ15440032617661544003261766.zip', group=581586298, priority=HIGH, headers={}, downloaded=27936146, total=83808446, status=DOWNLOADING, error=NONE, networkType=ALL, created=1544693355357, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={})
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.tonyodev.fetch2okhttp.OkHttpDownloader.execute(OkHttpDownloader.kt:53)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)`

**Comment by tonyofrancis** [comment]
@bangdinh it seems that the server is taking too long to respond. Create a custom OkhttpDownloader and pass it a custom okHttpClient with an increased readtimeout. 
```java
public class App extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(1)
                 .setHttpDownloader(getOkHttpDownloader())
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
    }

    private OkHttpDownloader getOkHttpDownloader() {
        final OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .readTimeout(20_000L, TimeUnit.MILLISECONDS) //increase read timeout as needed
                .connectTimeout(20_000L, TimeUnit.MILLISECONDS) //increase connection timeout as needed
                .build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL);
    }

}
```

**Comment by bangdinh** [comment]
The problem has been resolved. Thank Tony.!
Nice day.

**Comment by bangdinh** [comment]
#issue
 I download complete all file. When i minimize (or have one incoming call) -> all file in folder download have been deleted.
Can i help you! Thank.

**Comment by bangdinh** [comment]
`
    private void fetchConfiguration() {
        final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(activity)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(1)
                .setHttpDownloader(getOkHttpDownloader())
                .setNamespace(FETCH_NAMESPACE)
                .enableAutoStart(false)
//                .setNotificationManager(new DefaultFetchNotificationManager(activity))
                .build();

        fetch = Fetch.Impl.getInstance(fetchConfiguration).deleteAll();

    }

    private OkHttpDownloader getOkHttpDownloader() {
        final OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .readTimeout(3000, TimeUnit.MILLISECONDS) //increase read timeout as needed
                .connectTimeout(3000, TimeUnit.MILLISECONDS) //increase connection timeout as needed
                .writeTimeout(3000,TimeUnit.MILLISECONDS)
                .build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL);
    }`

**Comment by bangdinh** [comment]
` @Override
    public void onPause() {
        super.onPause();
        fetch.removeListener(fetchListener);
    `}`
    @Override
    public void onDestroy() {
        super.onDestroy();
        fetch.removeAll();
        fetch.close();
    }`

**Comment by jpvs0101** [comment]
I guess you should not call `fetch.removeAll();`.
Also why you use `fetch = Fetch.Impl.getInstance(fetchConfiguration).deleteAll();`?  
What is mean by `.deleteAll()` at the end?

**Comment by bangdinh** [comment]
Hi jpvs0101. Thank for help.
Right answer.

**Comment by bangdinh** [comment]
#issue :
when download complete file. i open file (share action)
Code:
````
 private void openFileShareAction(Attach attachShare) {
        File fileOpen = attachShare.getFile();
        Intent newIntent = new Intent(Intent.ACTION_VIEW);
        String mimeType = FileUtils.getMimeType(attachShare.getIMG());

        if (Build.VERSION.SDK_INT >= N) {
            Uri uri;
            if (fileOpen != null && fileOpen.exists()) {
                uri = FileProvider.getUriForFile(activity,
                        activity.getApplicationContext().getPackageName() + ".provider",////BuildConfig.APPLICATION_ID
                        fileOpen);
                newIntent.setDataAndType(uri, mimeType);
            } else {
                Toast.makeText(activity, getString(R.string.pieper_file_have_been_deleted), Toast.LENGTH_SHORT).show();
                return;
            }


        } else {
            newIntent.setDataAndType(Uri.fromFile(fileOpen), mimeType);
        }
        newIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_GRANT_READ_URI_PERMISSION);
        try {
            startActivity(newIntent);
        } catch (ActivityNotFoundException e) {
            e.printStackTrace();
        }

    }
````
=> App crash
Show log:
```
E/fetch2: FileDownloader downloads slice FileSlice(id=-1793271014, position=2, startBytes=11573548, endBytes=23147096, downloaded=0)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.tonyodev.fetch2okhttp.OkHttpDownloader.execute(OkHttpDownloader.kt:53)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
2018-12-14 15:57:54.997 1327-3680/com.piepme.android E/fetch2: FileDownloader downloads slice FileSlice(id=-1793271014, position=4, startBytes=34720644, endBytes=46294192, downloaded=0)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.tonyodev.fetch2okhttp.OkHttpDownloader.execute(OkHttpDownloader.kt:53)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
2018-12-14 15:57:55.017 1327-3681/com.piepme.android E/fetch2: FileDownloader downloads slice FileSlice(id=-1793271014, position=5, startBytes=46294192, endBytes=57867740, downloaded=0)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
        at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.tonyodev.fetch2okhttp.OkHttpDownloader.execute(OkHttpDownloader.kt:53)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
2018-12-14 15:57:55.187 1327-1327/com.piepme.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.piepme.android, PID: 1327
    java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.piepme.android.model.P300)
        at android.os.Parcel.writeSerializable(Parcel.java:1527)
        at android.os.Parcel.writeValue(Parcel.java:1475)
        at android.os.Parcel.writeList(Parcel.java:812)
        at android.os.Parcel.writeValue(Parcel.java:1424)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1423)
        at android.os.Bundle.writeToParcel(Bundle.java:1157)
        at android.os.Parcel.writeBundle(Parcel.java:764)
        at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:123)
        at android.os.Parcel.writeTypedArray(Parcel.java:1307)
        at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:619)
        at android.os.Parcel.writeParcelable(Parcel.java:1496)
        at android.os.Parcel.writeValue(Parcel.java:1402)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1423)
        at android.os.Bundle.writeToParcel(Bundle.java:1157)
        at android.os.Parcel.writeBundle(Parcel.java:764)
        at android.support.v4.app.FragmentState.writeToParcel(FragmentState.java:125)
        at android.os.Parcel.writeTypedArray(Parcel.java:1307)
        at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:619)
        at android.os.Parcel.writeParcelable(Parcel.java:1496)
        at android.os.Parcel.writeValue(Parcel.java:1402)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1423)
        at android.os.Bundle.writeToParcel(Bundle.java:1157)
        at android.os.Parcel.writeBundle(Parcel.java:764)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3710)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3851)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.io.NotSerializableException: com.tonyodev.fetch2.database.DownloadInfo
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
        at java.util.ArrayList.writeObject(ArrayList.java:734)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
2018-12-14 15:57:55.187 1327-1327/com.piepme.android E/AndroidRuntime:     at android.os.Parcel.writeSerializable(Parcel.java:1522)
        	... 34 more
2018-12-14 15:57:59.497 1327-1327/com.piepme.android E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:177)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:320)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:300)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1979)
2018-12-14 15:58:00.629 1327-3691/com.piepme.android E/fetch2: FileDownloader downloads slice FileSlice(id=137256314, position=6, startBytes=69840375, endBytes=83808446, downloaded=72383)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
2018-12-14 15:58:00.631 1327-3688/com.piepme.android E/fetch2: FileDownloader downloads slice FileSlice(id=137256314, position=4, startBytes=41904225, endBytes=55872300, downloaded=44061)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
2018-12-14 15:58:00.632 1327-3687/com.piepme.android E/fetch2: FileDownloader downloads slice FileSlice(id=137256314, position=3, startBytes=27936150, endBytes=41904225, downloaded=16384)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
2018-12-14 15:58:00.634 1327-3686/com.piepme.android E/fetch2: FileDownloader downloads slice FileSlice(id=137256314, position=2, startBytes=13968075, endBytes=27936150, downloaded=16384)
    java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:398)
        at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:205)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

**Comment by bangdinh** [comment]
Function getMimeType: 
 ```
public static String getMimeType(String url) {
        String type = null;
        String extension = MimeTypeMap.getFileExtensionFromUrl(url);
        if (extension != null) {
            type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
        }
        return type;
    }
```

**Comment by bangdinh** [comment]
When download complete. i back main activity (call downloading in FragmentDownload) and remove FragmentDownload. When comeback FragmentDownload (file exits) then open and not crash app.

**Comment by tonyofrancis** [comment]
@bangdinh have you resolved the problem?

**Comment by bangdinh** [comment]
@tonyofrancis  i fix problem when using fetch.removeAll() replace fetch.deleteAll().

**Comment by junior-jornada** [comment]
this works, but the files get corrupted on download. have any tips?
