### ISSUE TITLE
Not all files are downloading and logs are flooded with PriorityIterator backoffTime

### ISSUE THREAD

**Issue by td-jhackford** [tonyofrancis/Fetch#310]
I have a list of files (jpg, png, mp4, js, ect.) that need to be downloaded from AWS. Some of my files are downloaded without issue while most do not finish downloading. Either way my logs are flooded with "D/LibGlobalFetchLib: PriorityIterator backoffTime increased to 500 milliseconds". What is causing this and is it linked to my files that won't download?

**Comment by tonyofrancis** [comment]
@td-jhackford logging in Fetch is on by default. You can disable it using the the FetchConfiguration builder. The log `PriorityIterator backoffTime increased to 500 milliseconds` indicates that a new download or action in Fetch needs to be processed and the sleep timer is reset. This is likely due to the retying of the failed downloads. I will remove this log in the next version of the library.

**Comment by jpvs0101** [comment]
@tonyofrancis 
Is logging enabled for release build too?
or only for debug builds?

**Comment by tonyofrancis** [comment]
Logging in fetch is enabled by default for release and debug builds.

**Comment by jpvs0101** [comment]
Surprising, probably you should mention this in Readme, so those who doesn't want it can turn off.

**Comment by td-jhackford** [comment]
This issue is not so much that the logs are present, but that whatever is being "backedOff" is never resolved. The logs to increase the backoff time again and again just keep coming. If the downloads are being retried, they never succeed. If some other process is happening within Fetch, it never completes. How can I determine what is causing this and resolve it?

This is how I am implementing Fetch:
```
FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(mContext)
        .setDownloadConcurrentLimit(3)
        .build();
fetch = Fetch.Impl.getInstance(fetchConfiguration);`
Request request = new Request(url, filePath);
request.setPriority(Priority.HIGH);
request.setNetworkType(NetworkType.ALL);

FetchListener fetchListener = new FetchListener() {
//Lots of other overrides...
    @Override
    public void onCompleted(@NotNull Download download) {
        setDownloadProgress(getCurrentProgress() + 1);
    }
}

request.addListener(fetchListener);
    fetch.enqueue(request, updatedRequest -> {
    Log.v(log, "Fetch request was added successfully");
    fetch.removeListener(fetchListener);
}, (Error error) -> {
    Log.v(log, "Error adding request to Fetch queue");
});
```
Most recently I got a timeout error that started the "PriorityIterator backoffTime" logs...

```
01-03 13:29:19.898  E/LibGlobalFetchLib: FileDownloader download:DownloadInfo(id=1678830500, namespace='LibGlobalFetchLib', url='<https_url>', file='<file_path>', group=0, priority=HIGH, headers={}, downloaded=9642555, total=35807624, status=DOWNLOADING, error=NONE, networkType=ALL, created=1546547297827, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={})
    java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
        at com.android.tools.profiler.support.network.HttpTracker$InputStreamTracker.read(HttpTracker.java:105)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
        at com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.writeToOutput(SequentialFileDownloaderImpl.kt:262)
        at com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.run(SequentialFileDownloaderImpl.kt:119)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by tonyofrancis** [comment]
@td-jhackford The backoff logs are for internal use and will be frequent. Any action on Fetch will trigger a backoff and it does not only happen when a download fails. Sorry I was not clear in my earlier post. I have removed the log in the next version of Fetch. 

In regards to the timeout, this signals that the server is not responding fast enough. What you can do is increase the connection and or read timeout for okhttp. You can do this by providing the OkHttpDownloader your own OkHttpClient. Please see the sample app for an example.

**Comment by tonyofrancis** [comment]
@td-jhackford Fetch 2.3.5 have been released. Removed the annoying backoff logs. Logging is also disabled by default.
