### ISSUE TITLE
Download started from a foreground service failed when app is cleared from recents

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#314]
Using foreground service to start (also all download related operations) download.

**Issue:**
- Open app
- Start download
- Clear the app from recents
- After a few seconds the download failed
If the app is closed, but not cleared from recents download works correctly.

**Config**
Android 8.1
Fetch 2.3.4

```
 private OkHttpDownloader getOkHttpDownloader() {
        final OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .readTimeout(20, TimeUnit.SECONDS) //increase read timeout as needed
                .connectTimeout(20, TimeUnit.SECONDS) //increase connection timeout as needed
                .followRedirects(true)
                .followSslRedirects(true)
                .build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL);
    }


   final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .enableRetryOnNetworkGain(true)
                .enableAutoStart(false)
                .setProgressReportingInterval(1100)            
                .setHttpDownloader(getOkHttpDownloader())
                .enableLogging(BuildConfig.DEBUG)
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
```

**Logcat**
```
2019-01-06 18:38:48.388 12688-13189 D/LibGlobalFetchLib: DownloadManager starting download DownloadInfo(id=-1925543313, namespace='LibGlobalFetchLib', url='https://d-12.winudf.com/b/apk/Y29tLnNlYy5hbmRyb2lkLmFwcC5zYnJvd3Nlcl84MjAxMDIxMDBfYmQ4MmNkNDE?_fn=U2Ftc3VuZyBJbnRlcm5ldCBCcm93c2VyX3Y4LjIuMDEuMl9hcGtwdXJlLmNvbS5hcGs&_p=Y29tLnNlYy5hbmRyb2lkLmFwcC5zYnJvd3Nlcg&as=3b40c64dff6dce513ca0274023867e785c31fd71&c=1%7CCOMMUNICATION%7CZGV2PVNhbXN1bmclMjBFbGVjdHJvbmljcyUyMENvLiUyQyUyMCUyMEx0ZC4mdD1hcGsmdm49OC4yLjAxLjImdmM9ODIwMTAyMTAw&k=64822c481376287b26dbb84cae121cd95c357ef0', file='content://com.android.externalstorage.documents/document/primary%3A_____%2FSamsung%20Internet%20Browser_v8.2.01.2_apkpure.com.apk', group=0, priority=HIGH, headers={Cookie=__cfduid=dd721642ac101596d2127139629b30c611546779871, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36}, downloaded=20782253, total=64639042, status=QUEUED, error=NONE, networkType=ALL, created=1546779941593, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"true","KEY_DOWNLOAD_FILE_NAME":"Samsung Internet Browser_v8.2.01.2_apkpure.com.apk","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/68.0.3440.91 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.externalstorage.documents\/document\/primary%3A_____%2FSamsung%20Internet%20Browser_v8.2.01.2_apkpure.com.apk"})
2019-01-06 18:38:50.740 12688-12712 D/LibGlobalFetchLib: PriorityIterator backoffTime increased to 1 minute(s)
2019-01-06 18:39:50.804 12688-12712 D/LibGlobalFetchLib: PriorityIterator backoffTime increased to 2 minute(s)
2019-01-06 18:41:50.904 12688-12712 D/LibGlobalFetchLib: PriorityIterator backoffTime increased to 4 minute(s)
2019-01-06 18:42:39.184 12688-13197 E/LibGlobalFetchLib: FileDownloader downloads slice FileSlice(id=-1925543313, position=4, startBytes=32319519, endBytes=43092692, downloaded=8470011)
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47) 
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363) 
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407) 
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439) 
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-01-06 18:43:18.695 12688-13195 E/LibGlobalFetchLib: FileDownloader downloads slice FileSlice(id=-1925543313, position=1, startBytes=0, endBytes=10773173, downloaded=10730494)
    java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:409)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-01-06 18:43:18.922 12688-13189 E/LibGlobalFetchLib: FileDownloader download:DownloadInfo(id=-1925543313, namespace='LibGlobalFetchLib', url='https://d-12.winudf.com/b/apk/Y29tLnNlYy5hbmRyb2lkLmFwcC5zYnJvd3Nlcl84MjAxMDIxMDBfYmQ4MmNkNDE?_fn=U2Ftc3VuZyBJbnRlcm5ldCBCcm93c2VyX3Y4LjIuMDEuMl9hcGtwdXJlLmNvbS5hcGs&_p=Y29tLnNlYy5hbmRyb2lkLmFwcC5zYnJvd3Nlcg&as=3b40c64dff6dce513ca0274023867e785c31fd71&c=1%7CCOMMUNICATION%7CZGV2PVNhbXN1bmclMjBFbGVjdHJvbmljcyUyMENvLiUyQyUyMCUyMEx0ZC4mdD1hcGsmdm49OC4yLjAxLjImdmM9ODIwMTAyMTAw&k=64822c481376287b26dbb84cae121cd95c357ef0', file='content://com.android.externalstorage.documents/document/primary%3A_____%2FSamsung%20Internet%20Browser_v8.2.01.2_apkpure.com.apk', group=0, priority=HIGH, headers={Cookie=__cfduid=dd721642ac101596d2127139629b30c611546779871, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36}, downloaded=62293201, total=64639042, status=DOWNLOADING, error=NONE, networkType=ALL, created=1546779941593, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"true","KEY_DOWNLOAD_FILE_NAME":"Samsung Internet Browser_v8.2.01.2_apkpure.com.apk","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/68.0.3440.91 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.externalstorage.documents\/document\/primary%3A_____%2FSamsung%20Internet%20Browser_v8.2.01.2_apkpure.com.apk"})
    java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:409)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:439)
        at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl$downloadSliceFiles$1.run(ParallelFileDownloaderImpl.kt:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-01-06 18:43:24.015 12688-12688 D/LibGlobalFetchLib: PriorityIterator backoffTime reset to 500 milliseconds
2019-01-06 18:43:24.060 12688-12712 D/LibGlobalFetchLib: Removed listener com.myapplication.downloads.OHDownloadService$1@4519a2e
2019-01-06 18:43:24.096 12688-12716 W/Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
2019-01-06 18:43:24.100 12688-12716 D/vndksupport: Loading /vendor/lib/hw/gralloc.msm8916.so from current namespace instead of sphal namespace.
2019-01-06 18:43:24.521 12688-12712 D/LibGlobalFetchLib: PriorityIterator backoffTime increased to 1 minute(s)
```

**Comment by tonyofrancis** [comment]
@jpvs0101. Android 8 brought limitations to the way services work. Services now have a time limitation when the app is closed. Please read [Background Execution Limits ](https://developer.android.com/about/versions/oreo/background)

This was the reason behind Fetch not being implemented with a service, or me advising to use a service with Fetch because of the limitations. However, Fetch works great with services pre Android 8.  When the service(thread) is terminated by the Android system, the open socket will throw a read or connection timeout as it should.

**Comment by jpvs0101** [comment]
@tonyofrancis I am aware of that, but I am using a foreground service (Using `startForegroundService()`), NOT a background service. So I guess it is not the cause.

From my testing after opening this issue, it seems like context related issue.
I used `context.getApplicationContext()` before. So it causes this issue.
No I am using `activity.getApplication()`. It seems like working now.
But I am not 100% sure that the issue is related to this or solved or not!

**Comment by tonyofrancis** [comment]
@jpvs0101 This issue is not directly related to Fetch, but more to the Android system killing your service for some reason. Have a look at this [post](https://stackoverflow.com/questions/36324794/android-system-killed-my-service-when-i-clear-all-recent-app)

**Comment by jpvs0101** [comment]
@tonyofrancis It seems like service is running but download failed! :/
That is the confusing part!!

**Comment by tonyofrancis** [comment]
@jpvs0101 is the error related to the timeout or another error?. There is no recommended timeout setting but suggestions. Some servers take longer to respond than others and this can be based on several physical limitations such as network congestion etc.

**Comment by jpvs0101** [comment]
>  is the error related to the timeout or another error?

@tonyofrancis I don't exactly know that, just asked to try that option!

**Comment by tonyofrancis** [comment]
@jpvs0101 If you can provide sample code or an error I can better assist.
