### ISSUE TITLE
OutOfMemoryError after upgrade to 2.3.5

### ISSUE THREAD

**Issue by ar-** [tonyofrancis/Fetch#317]
Hi I'm using fetch2 in this open source app: https://gitlab.com/gdroid/gdroidclient/

I just tried to upgrade to 2.3.5 on a feature branch. So the only changes that I made locally are these:
```
    implementation "com.tonyodev.fetch2:fetch2:2.3.5"
    implementation "com.tonyodev.fetch2okhttp:fetch2okhttp:2.3.5"
```
Now I get an out of memory error that has not been there in 2.3.4

```
2019-01-11 07:13:03.149 18688-18823/org.gdroid.gdroid I/zygote64: Starting a blocking GC Alloc
2019-01-11 07:13:03.188 18688-18823/org.gdroid.gdroid I/zygote64: Alloc concurrent copying GC freed 193(32KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 142MB/148MB, paused 400us total 39.135ms
2019-01-11 07:13:03.188 18688-18823/org.gdroid.gdroid W/zygote64: Throwing OutOfMemoryError "Failed to allocate a 84601064 byte allocation with 6291456 free bytes and 49MB until OOM, max allowed footprint 155793512, growth limit 201326592"
2019-01-11 07:13:03.194 18688-18823/org.gdroid.gdroid E/AndroidRuntime: FATAL EXCEPTION: AppDownloader--1539417959
    Process: org.gdroid.gdroid, PID: 18688
    java.lang.OutOfMemoryError: Failed to allocate a 84601064 byte allocation with 6291456 free bytes and 49MB until OOM, max allowed footprint 155793512, growth limit 201326592
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:178)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:209)
        at okio.Buffer.readString(Buffer.java:713)
        at okio.Buffer.readString(Buffer.java:696)
        at okio.RealBufferedSource.readString(RealBufferedSource.java:200)
        at okhttp3.ResponseBody.string(ResponseBody.java:176)
        at com.tonyodev.fetch2okhttp.OkHttpDownloader.execute(OkHttpDownloader.kt:67)
        at com.tonyodev.fetch2core.FetchCoreUtils.getRequestSupportedFileDownloaderTypes(FetchCoreUtils.kt:235)
        at com.tonyodev.fetch2okhttp.OkHttpDownloader.getRequestSupportedFileDownloaderTypes(OkHttpDownloader.kt:173)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl.getFileDownloader(DownloadManagerImpl.kt:258)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl.getNewFileDownloaderForDownload(DownloadManagerImpl.kt:250)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:88)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-01-11 07:13:03.199 2542-18194/? W/ActivityManager:   Force finishing activity org.gdroid.gdroid/.MainActivity
2019-01-11 07:13:03.212 2542-2579/? I/ActivityManager: Showing crash dialog for package org.gdroid.gdroid u0
```

This is for a larger download of around 50 megabytes which is the apk file of the Fennec browser.

edit: error is reproducible by switching from 2.3.4 and 2.3.5 forward and backward

**Comment by tonyofrancis** [comment]
@ar- What happens when you test on a different device.? Do you get the same error?
Does this also happen with  2.3.4? The logs shared just show that okhttp was not able to read all of the stream because the device ran out of memory. This could happen for so many reason. Other apps using resources, memory leaks etc.

**Comment by kylealanr** [comment]
I've also had exactly the same issue for larger files, I'm using the library to download multiple GB video files and I get the OOM exception with 2.3.5, but it works fine when I downgrade to 2.3.4.

**Comment by tonyofrancis** [comment]
Only thing that really changed in the version is updating okhttp. What happens when httpurlconnection is used??

**Comment by tonyofrancis** [comment]
Fetch 2.3.6 has been released with a fix for the out of memory issue.

**Comment by imansdn** [comment]
this issue still exists for me on Fetch 3.1.6...
```
  implementation "androidx.tonyodev.fetch2:xfetch2:3.1.6"
  implementation "androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.6"
```
` 
java.lang.OutOfMemoryError: Could not allocate JNI Env
    at java.lang.Thread.nativeCreate(Thread.java)
    at java.lang.Thread.start(Thread.java:731)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
    at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl.downloadSliceFiles(ParallelFileDownloaderImpl.kt:419)
    at com.tonyodev.fetch2.downloader.ParallelFileDownloaderImpl.run(ParallelFileDownloaderImpl.kt:149)
    at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:103)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
`
```
user device:
Brand : samsung
Family :  SM-A750F
name :  Galaxy A7 (2018)
Kernel Version: 4.4.177-21528501
```
