### ISSUE TITLE
CursorWindowAllocationException After Downloading Multiple Files

### ISSUE THREAD

**Issue by gyurme-accedo** [tonyofrancis/Fetch#340]
Hi, 

we've noticed an odd issue in version 2.3.2 that results in failed downloads after many files have been downloaded.

## Current Behavior
After a number of files have been downloaded, downloads fail with a  `android.database.CursorWindowAllocationException` exception.

Our app downloads multiple files sequentially over time, and we do call fetch.close() and make a new instance of Fetch after a set of downloads are complete (typically a set of 4-5 files per set) before more downloads are queued. All downloads are done sequentially.

``` E/LibGlobalFetchLib: Fetch with namespace LibGlobalFetchLib error
    android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=649 (# cursors opened by this proc=649)
        at android.database.CursorWindow.<init>(CursorWindow.java:108)
        at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
        at com.tonyodev.fetch2.database.DownloadDao_Impl.get(DownloadDao_Impl.java:305)
        at com.tonyodev.fetch2.database.DatabaseManagerImpl.getDownloadsNoLock(DatabaseManagerImpl.kt:147)
        at com.tonyodev.fetch2.database.DatabaseManagerImpl.get(DatabaseManagerImpl.kt:141)
        at com.tonyodev.fetch2.fetch.FetchHandlerImpl.deleteAll(FetchHandlerImpl.kt:260)
        at com.tonyodev.fetch2.fetch.FetchImpl$deleteAll$1.invoke(FetchImpl.kt:434)
        at com.tonyodev.fetch2.fetch.FetchImpl$deleteAll$1.invoke(FetchImpl.kt:14)
        at com.tonyodev.fetch2.fetch.FetchImpl$executeDeleteAction$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:462)
        at com.tonyodev.fetch2.fetch.FetchImpl$executeDeleteAction$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:14)
        at com.tonyodev.fetch2core.HandlerWrapper$sam$i$java_lang_Runnable$0.run(HandlerWrapper.kt)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

Any help would be appreciated, we are currently trying with the newest version of Fetch (3.0.1) as well to see if this happens there as well.

It feels like somehow the Room / SQLLite cursors aren't being closed after downloads finish

**Comment by gyurme-accedo** [comment]
The code we use to download files is below, we kept it fairly light and added a reset Fetch method to see if that would help anything

```
class AssetDownloader @Inject constructor(val context: Context) : FetchListener {

    interface DownloadListener {
        fun onDownloadComplete()
        fun onProgress(downloadedPercentage: Int)
        fun onDownloadError(error: String)
    }

    var fetch: Fetch

    private var downloadListener: DownloadListener? = null

    init {
        setDefaultFetchConfig()
        fetch = Fetch.getDefaultInstance()
        resetFetch()
    }

    private fun setDefaultFetchConfig() {
        Fetch.setDefaultInstanceConfiguration(FetchConfiguration.Builder(context)
                .enableRetryOnNetworkGain(false)
                .setDownloadConcurrentLimit(1)
                .enableLogging(true)
                .setHttpDownloader(HttpUrlConnectionDownloader(Downloader.FileDownloaderType.SEQUENTIAL))
                .build())
    }

    fun resetFetch() {
        if (!fetch.isClosed) {
            fetch.close()
        }
        fetch = Fetch.getDefaultInstance()
        fetch.addListener(this)
    }

    /**
     * Download only 1 file at a time.
     * If you call this method previous download will be canceled and removed
     */
    fun startDownload(url: String, localFilePath: String, downloadListener: DownloadListener) {
        removeAllIncompleteDownloads()

        this.downloadListener = downloadListener

        //Delete the file in case there is a file with this name
        val localFile = File(localFilePath)
        localFile.delete()

        val request = Request(url, localFilePath)
        Timber.d("Fetch Data. Has active download = ${fetch.hasActiveDownloads}")
        Timber.d("Fetch Data. Is Closed = ${fetch.isClosed}")
        fetch.enqueue(request, Func {
        },
                Func {
                    Timber.d("Fetch Throwable Error  ${it.throwable} and Error  ${Error.valueOf(it.value).name}")
                    downloadListener.onDownloadError(Error.valueOf(it.value).name)
                })
    }


    override fun onAdded(download: Download) {
        Timber.d("onAdded ${download.url}")
    }

    override fun onCancelled(download: Download) {
        Timber.d("onCancelled ${download.url}")
    }

    override fun onCompleted(download: Download) {
        fetch.remove(download.id)
        fetch.close()
        downloadListener?.onDownloadComplete()
    }

    override fun onDeleted(download: Download) {
        Timber.d("onDeleted ${download.url}")
    }

    override fun onDownloadBlockUpdated(download: Download, downloadBlock: DownloadBlock, totalBlocks: Int) {
        Timber.d("onDownloadBlockUpdated ${download.url}")
    }

    override fun onError(download: Download, error: Error, throwable: Throwable?) {
        Timber.d("onError ${download.url}. Error is ${error.name}")
        downloadListener?.onDownloadError(
                "Download error. Downloading of ${download.url} failed with error: ${error.name}")
    }

    override fun onPaused(download: Download) {
        Timber.d("onPaused ${download.url}")
    }

    override fun onProgress(download: Download,
                            etaInMilliSeconds: Long,
                            downloadedBytesPerSecond: Long) {
        val percentageDownloaded = (100 * download.downloaded / download.total).toInt()
        Timber.d("onProgress ${download.url} PERCENTAGE IS $percentageDownloaded")
        downloadListener?.onProgress(percentageDownloaded)
    }

    override fun onQueued(download: Download,
                          waitingOnNetwork: Boolean) {
        Timber.d("onQueued ${download.url}")
    }

    override fun onRemoved(download: Download) {
        Timber.d("onRemoved ${download.url}")
    }

    override fun onResumed(download: Download) {
        Timber.d("onResumed ${download.url}")
    }

    override fun onStarted(download: Download,
                           downloadBlocks: List<DownloadBlock>,
                           totalBlocks: Int) {
        Timber.d("onStarted ${download.url}")
    }

    override fun onWaitingNetwork(download: Download) {
        Timber.d("onWaitingNetwork ${download.url}")
    }

    /**
     * This method removes all downloads that has not been completed.
     * Also deletes the files that are associated with incomplete downloads.
     */
    private fun removeAllIncompleteDownloads() {
        fetch.cancelAll()
        fetch.deleteAll()
        fetch.removeAll()
    }
}
```

**Comment by tonyofrancis** [comment]
@gyurme-accedo @gyurme-accedo gonna take a look and will post back.

**Comment by gyurme-accedo** [comment]
@tonyofrancis thanks, the issue seems to be gone now with the update to version 3.0.1 but we're still testing since it was a bit hard to reproduce the first time around.

**Comment by gyurme-accedo** [comment]
Unfortunately this issue has cropped up again for us, testing shows it still happens in 3.0.1 and 3.0.2 :(
It only happens after we load a number of files into a Realm database, and then use Fetch to download more files. 
 If we trigger a Fetch download for a second time though we don't get the exception.
