### ISSUE TITLE
Unable to add window -- token android.os.BinderProxy@9dde70e is not valid; is your activity running?

### ISSUE THREAD

**Issue by zeeshanzzz** [tonyofrancis/Fetch#366]
while enqueue in my code:
fetchConfiguration= new FetchConfiguration.Builder(getActivity())
                .setDownloadConcurrentLimit(3)
                .enableRetryOnNetworkGain(true).enableLogging(true)

                .build();

        fetch = Fetch.Impl.getInstance(fetchConfiguration);
       final List<Request> requests =new ArrayList<>();

        for(int i=0; i<modelList.size();i++){
            requests.add( new Request(modelList.get(i).getLink(), modelList.get(i).getType()));
            requests.get(i).setGroupId( requests.get(i).hashCode());

        }

        fetch.enqueue(requests, new Func<List<Pair<Request, Error>>>() {
                    @Override
                    public void call(@NotNull List<Pair<Request, Error>> result) {
                    String r=    result.get(result.size()).component2().getThrowable().getLocalizedMessage();
                    String req=result.get(result.size()).component1().getUrl();

                    }
                }
        );

i am getting this error:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.softec.videosaver, PID: 5034
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@8dadedb is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.widget.Toast$TN.handleShow(Toast.java:459)
        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by tonyofrancis** [comment]
@zeeshanzzz This error has nothing to do with Fetch but with your activity. A google search should lead you in the right direction.
