### ISSUE TITLE
request_not_successful while downloading mp3 file from Google Drive

### ISSUE THREAD

**Issue by andj207** [tonyofrancis/Fetch#475]
I'm trying to download mp3 file from Google Drive but Fetch always throw `request_not_successful `whilst Exoplayer can stream the mp3 very well. I've put then same request headers to Exoplayer and Fetch2 but only Exoplayer works.

    mapOf(
                            "Authorization" to "Bearer <my access token>"
                            , "Accept" to "*/*"
                            , "Accept-Encoding" to "gzip, deflate"
                            , "Connection" to "keep-alive"
                            , "User-Agent" to getString(R.string.user_agent_string)
                        )

Also setup with Cookie manager:

    val cookieJar: ClearableCookieJar =
            PersistentCookieJar(SetCookieCache(), SharedPrefsCookiePersistor(context))

        val okHttpClient = OkHttpClient.Builder()
            .cookieJar(cookieJar)
            .build()

    val fetchConfiguration = FetchConfiguration.Builder(context)
            .setHttpDownloader(OkHttpDownloader(okHttpClient))
            .setDownloadConcurrentLimit(downloadConfig.maxConcurrentDownloads)
            .setAutoRetryMaxAttempts(MAX_RETRY)
            .build()

    Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration)

        fetch = Fetch.Impl.getDefaultInstance()

Exception:

    com.tonyodev.fetch2.exception.FetchException: request_not_successful
        at com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.run(SequentialFileDownloaderImpl.kt:133)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by andj207** [comment]
It's my bad, the token has been altered in another func before passing to Fetch so authentication failed.
