### ISSUE TITLE
Fetch crashes with SSL error BAD_DECRYPT

### ISSUE THREAD

**Issue by joelphilippage** [tonyofrancis/Fetch#524]
Downloads occasionally crash part way through with this error:
```
2020-09-13 08:07:30.906 12835-13267/com.turndapage.navcasts E/LibGlobalFetchLib: FileDownloader download:DownloadInfo(id=-274817350, namespace='LibGlobalFetchLib', url='https://traffic.omny.fm/d/clips/aaea4e69-af51-495e-afc9-a9760146922b/9298412b-3686-41ef-ae8e-aaa80008d149/1d91228d-c9a8-4864-a9e1-ac31018a3a44/audio.mp3?utm_source=Podcast&in_playlist=97a99509-3667-475e-b2f0-aaa80008d14e', file='/storage/emulated/0/Android/data/com.turndapage.navcasts/files/Podcasts/Unspooled/Rebel Without A Cause.mp3', group=-1079899346, priority=NORMAL, headers={}, downloaded=103972427, total=104948642, status=DOWNLOADING, error=NONE, networkType=ALL, created=1600009599628, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=1001568891, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=2000, downloadedBytesPerSecond=3420434)
    javax.net.ssl.SSLProtocolException: Read error: ssl=0xd5db6dc8: Failure in SSL library, usually a protocol error
    error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (external/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1307 0xdcc2ba43:0x00000000)
    error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (external/boringssl/src/ssl/tls_record.cc:298 0xdcc2ba43:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
        at com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.writeToOutput(SequentialFileDownloaderImpl.kt:280)
        at com.tonyodev.fetch2.downloader.SequentialFileDownloaderImpl.run(SequentialFileDownloaderImpl.kt:128)
        at com.tonyodev.fetch2.downloader.DownloadManagerImpl$start$$inlined$synchronized$lambda$1.run(DownloadManagerImpl.kt:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

This is not sent to the fetch handler so I'm not sure how to catch this and recover from it.

**Comment by tonyofrancis** [comment]
@joelphilippage This looks like an okhttp client error. Can you create your own OkHttpDownloader and pass that to Fetch for testing?

```java
  private OkHttpDownloader getOkHttpDownloader() {
        final OkHttpClient okHttpClient = new OkHttpClient.Builder().build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL);
    }

    final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                //.setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .setHttpDownloader(getOkHttpDownloader())
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
```
