### ISSUE TITLE
Database is locked ?

### ISSUE THREAD

**Issue by thib-rdr** [tonyofrancis/Fetch#569]
Hi, 

Without any modifications to my code, after upgrading to the last version of Fetch, I get an error on request enqueue, that prevents downloading files.

```
    implementation 'androidx.tonyodev.fetch2:xfetch2:3.1.6'
    implementation "androidx.tonyodev.fetch2okhttp:xfetch2okhttp:3.1.6"
```
```

2021-03-08 10:24:19.988 E/BZFetch: Fetch with namespace BZFetch error
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
        at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325)
        at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
        at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
        at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:478)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransaction(FrameworkSQLiteDatabase.java:69)
        at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:354)
        at com.tonyodev.fetch2.database.DownloadDao_Impl.delete(DownloadDao_Impl.java:247)
        at com.tonyodev.fetch2.database.FetchDatabaseManagerImpl.delete(FetchDatabaseManagerImpl.kt:66)
        at com.tonyodev.fetch2.database.FetchDatabaseManagerWrapper.delete(FetchDatabaseManagerWrapper.kt:52)
        at com.tonyodev.fetch2.fetch.FetchHandlerImpl.removeDownloads(FetchHandlerImpl.kt:312)
        at com.tonyodev.fetch2.fetch.FetchHandlerImpl.removeAll(FetchHandlerImpl.kt:299)
        at com.tonyodev.fetch2.fetch.FetchImpl$removeAll$1.invoke(FetchImpl.kt:415)
        at com.tonyodev.fetch2.fetch.FetchImpl$removeAll$1.invoke(FetchImpl.kt:16)
        at com.tonyodev.fetch2.fetch.FetchImpl$executeRemoveAction$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:443)
        at com.tonyodev.fetch2.fetch.FetchImpl$executeRemoveAction$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:16)
        at com.tonyodev.fetch2core.HandlerWrapper$sam$i$java_lang_Runnable$0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```

I'll try to dig up, but that's very odd, as I sometimes have this error, sometimes just nothing happens... I'll try to dig up the code, and see what is the problem, but if someone has the same bug and has found the source, that'd be great.
Thanks

**Comment by thib-rdr** [comment]
Just a quick comment, the culprit seems to be `fetch.removeAll();`

**Comment by thib-rdr** [comment]
I'm still having this problem, sometimes with calls to `fetch.resumeGroup(FETCH_GROUP_ID);`, for some reason and the thing is I can't catch this error because the exception is not propagated to my code...

**Comment by jemshit** [comment]
Same with `.deleteAll()`. Error does not go away even if fetch is closed and new fetch is created with same namespace

**Comment by thib-rdr** [comment]
I ended up downgrading Fetch to v3.1.4, the latest version that didn't have the problem...
