### ISSUE TITLE
[BUG] repalceExtras not working

### ISSUE THREAD

**Issue by tatsuya25** [tonyofrancis/Fetch#590]
when using replaceExtras it throws with java.lang.IllegalArgumentException: Too many bind arguments.  2 arguments were provided but the statement needs 1 arguments.

**Comment by andj207** [comment]
I have this issue too 

    java.lang.IllegalArgumentException: Too many bind arguments.  2 arguments were provided but the statement needs 1 arguments.
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:72)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1920)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1898)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:247)
        at com.tonyodev.fetch2.database.FetchDatabaseManagerImpl.updateExtras(FetchDatabaseManagerImpl.kt:116)
        at com.tonyodev.fetch2.database.FetchDatabaseManagerWrapper.updateExtras(FetchDatabaseManagerWrapper.kt:160)
        at com.tonyodev.fetch2.fetch.FetchHandlerImpl.replaceExtras(FetchHandlerImpl.kt:475)
        at com.tonyodev.fetch2.fetch.FetchImpl$replaceExtras$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:784)
        at com.tonyodev.fetch2.fetch.FetchImpl$replaceExtras$$inlined$synchronized$lambda$1.invoke(FetchImpl.kt:16)
        at com.tonyodev.fetch2core.HandlerWrapper$sam$i$java_lang_Runnable$0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by rahbadev** [comment]
you need edit FetchDatabaseManagerImpl.kt Class

replace ${DownloadDatabase.COLUMN_EXTRAS} = '?' 
by ${DownloadDatabase.COLUMN_EXTRAS} = ?

this method modify it

    override fun updateExtras(id: Int, extras: Extras): DownloadInfo? {
        throwExceptionIfClosed()
        database.beginTransaction()
        database.execSQL(
            "UPDATE ${DownloadDatabase.TABLE_NAME} SET "
                    + "${DownloadDatabase.COLUMN_EXTRAS} = ? "
                    + "WHERE ${DownloadDatabase.COLUMN_ID} = ?",
            arrayOf(extras.toJSONString(), id)
        )
        database.setTransactionSuccessful()
        database.endTransaction()
        val download = requestDatabase.requestDao().get(id)
        sanitize(download)
        return download
    }

**Comment by stleusc** [comment]
Does that not look like a simple bugfix?

I guess the '' around the ? are simply wrong.
Can anyone fix this?
