### ISSUE TITLE
android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by arashfat** [tonyofrancis/Fetch#652]
Hello recently I saw a log in Firebase crashlytics that says: 

 android.database.sqlite.SQLiteException: no such table: requests (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT * FROM requests, (OS error - 2:No such file or directory)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:948)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:559)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1493)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1463)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:161)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:446)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at com.tonyodev.fetch2.database.DownloadDao_Impl.get(DownloadDao_Impl.java:299)
	at com.tonyodev.fetch2.database.FetchDatabaseManagerImpl.get(FetchDatabaseManagerImpl.java:120)
	at com.tonyodev.fetch2.database.FetchDatabaseManagerImpl$sanitizeOnFirstEntry$1.invoke(FetchDatabaseManagerImpl.java:239)
	at com.tonyodev.fetch2.database.FetchDatabaseManagerImpl$sanitizeOnFirstEntry$1.invoke(FetchDatabaseManagerImpl.java:20)
	at com.tonyodev.fetch2.fetch.LiveSettings.execute(LiveSettings.java:12)
	at com.tonyodev.fetch2.database.FetchDatabaseManagerImpl.sanitizeOnFirstEntry(FetchDatabaseManagerImpl.java:237)
	at com.tonyodev.fetch2.database.FetchDatabaseManagerWrapper.sanitizeOnFirstEntry(FetchDatabaseManagerWrapper.java:153)
	at com.tonyodev.fetch2.fetch.FetchHandlerImpl.init(FetchHandlerImpl.java:46)
	at com.tonyodev.fetch2.fetch.FetchImpl$1.invoke(FetchImpl.java:59)
	at com.tonyodev.fetch2.fetch.FetchImpl$1.invoke(FetchImpl.java:16)
	at com.tonyodev.fetch2core.HandlerWrapper$sam$i$java_lang_Runnable$0.run(HandlerWrapper.java:2)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)

I'm using version 3.1.5

**Comment by tonyofrancis** [comment]
@arashfat is this still an issue you face with the latest version?
