### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by AdamFM** [tonyofrancis/Fetch#67]
E/SQLiteLog: (2067) abort at 31 in [INSERT INTO requests ( _id, _url, _file_path, _status, _headers, _written_bytes, _file_size, _error, _priority ) VALUES ( 117505259219586, 
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: requests._file_path (code 2067)
at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1678)
at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1607)
at com.tonyodev.fetch.DatabaseHelper.insert(DatabaseHelper.java:168)
at com.tonyodev.fetch.DatabaseHelper.insert(DatabaseHelper.java:126)
at com.tonyodev.fetch.Fetch.enqueue(Fetch.java:301)

i download file.. then i delete.. when i download again.. that is show this error
*sorry for my bad english

**Comment by AdamFM** [comment]
from file manager in android..

**Comment by tonyofrancis** [comment]
@AdamFM Before insert call `fetch.get(request)` to find out if the request already exist. If it does, call `fetch.remove(id)` to remove the request from fetch then proceed to insert it.
