### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by VitorAndrioli** [tonyofrancis/Fetch#68]
From my Crashlytics I got a 

> Fatal Exception: java.util.ConcurrentModificationException 

on 

> com.tonyodev.fetch.Fetch$4.onReceive (Fetch.java:971)

Crashlytics doesn't really give me information on what was done before getting there, so it's a bit hard for me to debug. Any ideas on what may be causing this?

Thanks.

**Comment by tonyofrancis** [comment]
@VitorAndrioli from what I can gather, It seems that this issue is occurring inside the broadcast receiver that publishes download progress updates to the Fetch Listeners. I have a feeling the the array list that holds the listeners gets modified. (A listener gets removed or added) whiles trying to publish the updates to all attached listeners. Ill look into this more closely and should have a fix for next release. Thanks

**Comment by riadhnet** [comment]
i got the same error here is the logcat
`08-22 21:02:36.891 8904-8904/br.com.vrtu.androidapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: br.com.vrtu.androidapp, PID: 8904
                                                                      java.util.ConcurrentModificationException
                                                                          at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                          at com.tonyodev.fetch.Fetch$4.onReceive(Fetch.java:1016)
                                                                          at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                          at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                          at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

`08-22 21:05:34.021 8904-9141/br.com.vrtu.androidapp W/System.err: java.net.ProtocolException: unexpected end of stream
08-22 21:05:34.031 8904-9141/br.com.vrtu.androidapp W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:469)
08-22 21:05:34.031 8904-9141/br.com.vrtu.androidapp W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:374)
08-22 21:05:34.031 8904-9141/br.com.vrtu.androidapp W/System.err:     at java.io.InputStream.read(InputStream.java:162)
08-22 21:05:34.041 8904-9141/br.com.vrtu.androidapp W/System.err:     at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
08-22 21:05:34.041 8904-9141/br.com.vrtu.androidapp W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
08-22 21:05:34.041 8904-9141/br.com.vrtu.androidapp W/System.err:     at com.tonyodev.fetch.FetchRunnable.writeToFileAndPost(FetchRunnable.java:259)
08-22 21:05:34.041 8904-9141/br.com.vrtu.androidapp W/System.err:     at com.tonyodev.fetch.FetchRunnable.run(FetchRunnable.java:148)
08-22 21:05:34.041 8904-9141/br.com.vrtu.androidapp W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-22 21:05:40.001 8904-8910/br.com.vrtu.androidapp W/art: Suspending all threads took: 8.236ms`

what i'm doing is when i open the app again , and there is a downloading request , i add listener again to get updates

**Comment by tonyofrancis** [comment]
@riadhnet thanks for reporting. Ill get a fix together and try to push an update soon

**Comment by frameset** [comment]
Is there any workaround that can be used in the meantime?

**Comment by tonyofrancis** [comment]
@VitorAndrioli @riadhnet  This bug has now been fixed in 1.1.4
