### ISSUE TITLE
UNIQUE constraint failed: requests._file_path

### ISSUE THREAD

**Issue by henrystivens** [tonyofrancis/Fetch#70]
I have a list of images that should be downloaded every time I start the application, the first time you download them correctly but the second time the application no longer downloads them because there is an sqlite exception:

```
E/SQLiteLog: (2067) abort at 116 in [INSERT INTO requests ( _id, _url, _file_path, _status, _headers, _written_bytes, _file_size, _error, _priority ) VALUES ( 260715679710510, 'http://192.168.1.103:8088/img/upload/enfermedad/1/im
W/System.err: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: requests._file_path (code 2067)
W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
W/System.err:     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
W/System.err:     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
W/System.err:     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
W/System.err:     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
W/System.err:     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
W/System.err:     at com.tonyodev.fetch.DatabaseHelper.insert(DatabaseHelper.java:168)
W/System.err:     at com.tonyodev.fetch.Fetch.enqueue(Fetch.java:398)
W/System.err:     at com.pcasistencias.unaluva.ui.SplashActivity.saveData(SplashActivity.java:170)
W/System.err:     at com.pcasistencias.unaluva.ui.SplashActivity$1.onResponse(SplashActivity.java:91)
W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5238)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
W/System.err: com.tonyodev.fetch.exception.EnqueueException: UNIQUE constraint failed: requests._file_path (code 2067)
W/System.err:     at com.tonyodev.fetch.DatabaseHelper.insert(DatabaseHelper.java:176)
W/System.err:     at com.tonyodev.fetch.Fetch.enqueue(Fetch.java:398)
W/System.err:     at com.pcasistencias.unaluva.ui.SplashActivity.saveData(SplashActivity.java:170)
W/System.err:     at com.pcasistencias.unaluva.ui.SplashActivity$1.onResponse(SplashActivity.java:91)
W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5238)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
```
My Code:
```java
private List<Request> photoRequests = new ArrayList<>();
//Add requests...
//Then download
Fetch fetch = Fetch.newInstance(this);
fetch.addFetchListener(this);
fetch.enqueue(photoRequests);
fetch.release();
```

Thanks!

**Comment by tonyofrancis** [comment]
Fetch does not allow you to enqueue/insert the same request more than once. Fetch maintains a database of all requests that were inserted. Your code needs to handle the first enqueue/insert and should resume downloading a request if it already exists in the Fetch database. You can go about this several ways. 

1. To resume downloads on application startup call 'Fetch.startService(context)'. You can call this in your application's onCreate method.
2. You can check if a request is already handled by Fetch and insert it if it's not. Call 'fetch.contains(request)'. This method will let you know if a request is already handled/exist. If the request does not exist you can then proceed to insert it. Hope this helps.

**Comment by henrystivens** [comment]
In the event that the file or image is updated on the server, could not download it again?

**Comment by tonyofrancis** [comment]
Yes. What you can do is delete the first request from fetch by calling `fetch.removeRequest(id)`. The request will be deleted but not the file.

**Comment by henrystivens** [comment]
Yes, I used `fetch.removeRequests();` and the app worked.

Thanks again.
